Feat: 설문조사 기능을 적용합니다.
kimerukorea/kimeru-client pull request #15
Opened 2023-05-18 19:04 UTC by po4tion

127.0.0.1:3000/survey-list 경로에서 설문조사를 진행할 수 있습니다.

2023-05-20 05:07 UTC, ChanhyukPark-Tech requested changes
survey Final.hooks.ts 부분은 오늘 저녁에 볼게용~~

2023-05-20 05:07 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/landing/Landing.hooks.ts
> +};
비슷한 기능을 하는데 추상화 기능이 섞여있어요,

메인 페이지 가기, 시작하기를 클릭했을때 기능들이 이 useCTAButton 훅에 섞여있는데
시작하기에 해당하는것은 useStartButton 훅으로 분리해서 추상화가 되어있는데
메인 페이지 가기에 해당하는 기능은 useCTAButton 훅 내부에서 기능을 구현해서 덜 추상화가 됐어요 
추상화를 많이하거나, 조금하거나는 괜찮지만 일관성을 지키는게 좋을 것 같아요. 추상화 수준을 맞춰주세요!

2023-05-20 05:07 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/landing/Landing.hooks.ts
> +  };
useMoveOtherContents 훅에 의구심이 드는게 키메루 프로젝트를 처음보거나, 혹은 유지보수를 하는사람이 처음 코드를봤을떄

```tsx
const {replace} = useRouter()

const onMoveOtherContents = () => {
replace('/survey-list')
}
```

위 코드랑 지금 구현되있는 코드랑 비교했을때 가독성이 더 좋은 코드가 어떤건가요?

현재 구현되있는 코드는 `멋진` 코드이지, `가독성`좋은 코드는 아니라고 생각이들었어요 😁

2023-05-20 05:07 UTC, ChanhyukPark-Tech commented on src/apps/survey/hooks/useGetSurveyId.ts
> +    surveyId: surveyId ?? DEFAULT_SURVEY_ID,
이런경우 surveyId는 SSR시점에 null이 아닌걸 확신할 수 있기때문에( not found로 보내는로직)
여기서 non-null assertion을 사용해도 합리적이지 않나용?

2023-05-20 05:07 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.hooks.ts
> +  const [convertFetchDataToChartData, _] = useState(() => {
```suggestion
  const [convertFetchDataToChartData] = useState(() => {
```

2023-05-20 05:07 UTC, ChanhyukPark-Tech requested changes
survey Final.hooks.ts 부분은 오늘 저녁에 볼게용~~

2023-05-20 05:20 UTC, po4tion commented
> survey Final.hooks.ts 부분은 오늘 저녁에 볼게용~~

감사합니다!!!

2023-05-20 05:59 UTC, ChanhyukPark-Tech requested changes

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/apis/getSurveyListById.ts
> +export const getSurveyListById = async ({ surveyId }: SurveyId) => {
이 함수의 이름에 왜 List라는 워딩이 들어가나요?
설문조사 목록을 불러오는것이 아닌, 특정 설문조사 하나만 가져오는것 아닌가요?
그러면 List가 아닌것 같아요!😁

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/apis/getSurveyMainList.ts
> +import type { SurveyId } from "./types";
good😃👍

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.hooks.ts
> +  const { data: surveyFinalList } = useSurveyFinalListQuery(true);
isFinalQuestion boolean을 왜넘겨줘야해요?

![image](https://github.com/kimerukorea/kimeru-client/assets/69495129/dbb36ab9-57ae-4c0a-ad39-d6a0fbf3da20)

이미지 출처 : https://mangkyu.tistory.com/45

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.hooks.ts
> +  const { data: surveyListById } = useSurveyListByIdQuery();
```suggestion
  const { data: surveyInfo } = useSurveyListByIdQuery();
```

정도가 data를 나타내기 적합한 용어같네용 더이상 ById라는 맥락은 필요없어졌으니까요 data에는

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.hooks.ts
> +          비율: Number(
설문조사 완료페이지에서
![image](https://github.com/kimerukorea/kimeru-client/assets/69495129/0257b085-d56a-43f3-97c8-59abaa23bedc)

위와같은 오류를 만났어요!

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.tsx
> +      </BottomButtonGroup>
버튼 아래에 너무 붙어있어요. 다른 페이지와 일관되게 띄워주세요

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.tsx
> +    <VStack backgroundColor="white">
마지막 결과페이지도 키메루의 배경색을 사용해주세요!

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.hooks.ts
> +  const [convertFetchDataToChartData, _] = useState(() => {
꼭 useState를 사용해야해요? set을 안하는데,,
useMemo를쓰면안되나요?

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.hooks.ts
> +          비율: Number(
랜덤으로 색을 선택할때 에러케이스가 있는것같아요

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/final/Final.tsx
> +                </Bar>
good

2023-05-20 05:59 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/main/question/Question.hooks.ts
> +    if (answers) {
이 if문 왜필요한가요?
answers는 non null 배열 아닌가요??!

2023-05-22 13:58 UTC, po4tion commented on src/constants/Sizes.ts
> +} as const;
해당 값들이 두 곳에서 사용하고 있어서 앞으로 모든 로고들이 고정된 width와 height 값을 가진다고 판단하여 공통으로 쓰일 constants에 정의하였습니다. 찬혁님의 의도대로라면 각 도메인마다 각기 다른 로고 사이즈를 가질 수 있다고 판단되네요. 그러하여 해당 로고들의 사이즈는 우연의 일치로 같아졌기 때문에 공통 모듈을 제거해봤습니다. 
[fix: remove common module -constants file](https://github.com/kimerukorea/kimeru-client/pull/15/commits/8f94602b9691e8abb9b0b6f97143def66047862f)

2023-05-22 14:13 UTC, po4tion commented on src/hooks/useMoveOtherContents.ts
> +};
1. replace 함수와의 차이점에 대한 설명드립니다.
`replace` 함수를 쓰게 된다면 클릭 이벤트에 적용시, `onClick={() => replace("/")}`와 같이 적용됩니다. 반면 `onMoveOtherContents` 함수는 VoidFunction이기에 onClick={onMoveOtherContents}와 같이 사용할 수 있습니다. 이는 렌더링 시에 함수를 한번만 생성하게 하여 성능에 유리하다고 생각하여 작성하였습니다. 또한 사용하는 쪽에서는 이동한다는 의미만 알고 있으면 hook과 ui 분리가 더욱 완벽해진다고 생각하였습니다.

2. contents라는 네이밍에 대한 설명 드립니다.
contents라는 네이밍을 지은 이유는 각 페이지마다 담고 있는 내용물(영어로 번역시 contents)을 의미하는 변수명으로 사용하였습니다. 하지만 찬혁님처럼 헷갈려하시는 분이 계셔 이건 명료하지 못하다고 생각하여 네이밍을 contents -> path로 변경해봤습니다.
[fix: useMoveOtherContents 네이밍 변경 -> useMoveOtherPath](https://github.com/kimerukorea/kimeru-client/pull/15/commits/d0779d880998751a15998ba378aa24c76a49195d)

2023-05-22 14:24 UTC, po4tion commented on src/stores/step/index.ts
> +export * from "./step.types";
답변드립니다.

step은 Zustand로 구성된 전역 상태 관리 구성원으로 퀴즈와 설문조사 사이를 이동하는 과정에서 초기화가 이루어져 서로 다른 도메인간에 충돌이 있을수는 없습니다. 또한 유지보수 측면에서도 initialState의 currentStep에 최대값 제한이 걸려있지 않아 도메인끼리 가질 수 있는 step이 서로 다르더라도 유지보수 측면에서 우려될 사항은 없을 것으로 사료됩니다.

2023-05-22 14:28 UTC, po4tion commented on src/types/supabase.ts
> +};
1. 이렇게 바꾼 이유에 대한 설명 드립니다.
Supabase의 Json 타입을 너무나도 사용하고 싶어. 타입을 직접 수동으로 바꿨습니다.

2. 휴먼에러에 대한 답변 드립니다.
Supabase에서 제공하는 타입 파일을 그대로 copay&paste 할 시 휴먼에러가 발생할 수 있습니다. 그러나 Supabase의 타입 변환 시스템의 허점 때문에 개발자의 의도대로 개발하지 못하는 상황이 맞는건지 생각이 듭니다. 기술에 휘둘리는 개발자가 되는 것 같아서요.

2023-05-22 14:29 UTC, po4tion commented on src/apps/quiz/components/quiz-page/landing/Landing.hooks.ts
> +import { useStepStore } from "@/stores";
https://github.com/kimerukorea/kimeru-client/pull/15#discussion_r1200591695

답변드렸습니다.

2023-05-22 14:30 UTC, po4tion commented on src/apps/survey/components/main/final/Final.hooks.ts
> +  const [convertFetchDataToChartData, _] = useState(() => {
[fix: useState의 사용하지 않는 setState를 제거합니다.](https://github.com/kimerukorea/kimeru-client/pull/15/commits/4dde8ec875594ccc25f62391cac0ed0a59779a32)

감사합니다.

2023-05-23 11:40 UTC, po4tion commented on src/apps/survey/components/landing/Landing.hooks.ts
> +};
좋은 의견 감사드립니다!
[fix: useCTAButton 내의 hook들의 추상화 수준을 일관성을 지키도록 변경합니다.](https://github.com/kimerukorea/kimeru-client/pull/15/commits/a68b5aad024395db318957a27d6da1e5681602c6)

질문을 하나 드리고자 합니다. 만약에 `useMoveOtherContents()`처럼 사용되는 hook이었다면 추상화 수준이 useStartButton()과 동일하다고 말할 수 있나요?

2023-05-23 11:52 UTC, po4tion commented on src/apps/survey/components/landing/Landing.hooks.ts
> +  };
좋은 의견 감사드립니다! 해당 hook은 path 값만 제외하면 동일한 코드가 이곳저곳에서 사용되던 것을 보고 재활용 해야겠다는 생각이 들어 만들었던 기억이 납니다. 하지만 비슷한 구조를 가지는 코드라도 코드의 가독성까지 헤치면서 코드 최적화를 하는 것이 별로라는 것을 이번에 배웠네요.

[fix: useMoveOtherPath hook을 삭제하고 더 읽기 쉬운 코드로 변경합니다.](https://github.com/kimerukorea/kimeru-client/pull/15/commits/db64b83eda03495b07f86f51bc4f9e3601c01322)

2023-05-23 12:02 UTC, po4tion commented on src/apps/survey/hooks/useGetSurveyId.ts
> +    surveyId: surveyId ?? DEFAULT_SURVEY_ID,
너무 많은 생각을 하느라 non-null assertion을 아예 생각도 안하고 있었네요. 찬혁님 말씀처럼 getServerSideProps에서 surveyId 값이 없으면 notFound page(404 페이지)로 이동되기 때문에 무조건 surveyId가 있을 수 밖에 없죠!

[fix: useGetSurveyId의 return 값을 널 병합 연산자를 제거하고 non-null 단언 연산자를 사용합니다.](https://github.com/kimerukorea/kimeru-client/pull/15/commits/77275e55e3d61b179cf56026da22ab6043475a5a)

2023-05-23 12:11 UTC, po4tion commented on src/apps/survey/apis/getSurveyListById.ts
> +export const getSurveyListById = async ({ surveyId }: SurveyId) => {
답변드립니다!

1. 함수의 이름에 List가 들어가는 이유
Supabase의 테이블 이름이 surveyList여서 그대로 차용을 했습니다. 그런데 Id를 기준으로 단 하나만 가져오는 것이니 List라는 단어는 별로 어울리지 않아 보이네요. 수정하였습니다!

[fix: getSurveyListById의 기능은 단 하나의 survey 아이템을 가져오는 것이므로 getSurveyById…](https://github.com/kimerukorea/kimeru-client/pull/15/commits/919c4c7e7751bcc727246ec8e6bc177ad326d6bb)

2023-05-23 12:32 UTC, po4tion commented on src/apps/survey/components/main/final/Final.hooks.ts
> +  const { data: surveyFinalList } = useSurveyFinalListQuery(true);
답변드립니다.
boolean 값을 넘겨주는 이유는 마지막 문제일 경우에만 데이터를 호출시키고 싶었습니다(이곳 말고도 다른 곳에서 사용중입니다). 주신 자료는 잘 보았습니다. 근데 useQuery 자체가 이미 다양한 역할을 하도록 설계된 hook 아닌가요?

2023-05-23 12:59 UTC, po4tion commented on src/apps/survey/components/main/final/Final.hooks.ts
> +          비율: Number(
https://github.com/kimerukorea/kimeru-client/pull/15#discussion_r1202284282

해당 과정에서 에러케이스가 수정되었습니다.

2023-05-23 14:44 UTC, ChanhyukPark-Tech commented on src/apps/survey/components/landing/Landing.hooks.ts
> +};
추상화 수준을 정확히 정의할수는 없어서 정확한 답변이 되기는 어려울 것 같네요.
useStartButton은 param을 하나도 안받고, useMoveOtherContents 는 path라는 param을 받아서 추상화 수준이 약간 다를 수 있겠네요. param을 아예안받는 useMoveOtherContents을 useMoveOtherContentsMainPage 정도 훅으로 강력하게 추상화하면 비슷한 추상화 수준이라고 볼 수 있을 것 같아요

2023-05-23 14:48 UTC, ChanhyukPark-Tech approved these changes

2023-05-23 14:48 UTC, merged